# Generated by Django 5.0 on 2023-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_alter_purchaseorder_id_alter_vendor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="fulfilment_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="vendor",
            name="quality_rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="vendor",
            name="response_time",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
