# Generated by Django 5.0 on 2023-12-09 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vendors",
            "0003_vendor_fulfilment_rate_vendor_on_time_delivery_rate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="quality_rating",
        ),
        migrations.RemoveField(
            model_name="vendor",
            name="response_time",
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="acknowledgment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="items",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(),
        ),
    ]
